download: # 下载股票数据集
  base_data_path: quotes # 基础数据集存放路径（开盘价，收盘价......）
  base_data_path_pro: quotes_ok  # 基础数据集处理后存放路径（将None转为-9999）
  extended_dataset_path: peTTM    # 扩展数据集存放路径（市盈率，市净率......）
  SHA_name: sh.csv # 上证指数文件名
  SZSE_name: sz.csv # 深证成指文件名
  today_wangyi: wangyi.csv # 网易今日所有股票数据集文件名
  today_sina: sina.csv # 新浪今日所有股票数据集文件名
  mat_all: StockQFQ.mat  # 股票数据集 mat 文件最终命名
  mat_update: StockQFQ_update.mat # 股票数据集 mat 文件临时命名



conversion: # 转换数据集
  last_days: 7 # 过去多少天的数据作为特征
  predict_days: 1 # 预测多少天的数据
  delete_days: 0 # 删除多少天的数据
  train_test_split: 0.8 # 训练集测试集划分比例
  train_val_split: 0.8 # 训练集验证集划分比例
  train_data_path: train_data.csv # 训练集存放路径
  test_data_path: test_data.csv # 测试集存放路径
  val_data_path: val_data.csv # 验证集存放路径

  

training: # 训练
  use_gpu: True # 是否使用GPU
  batch_size: 128 # 批大小
  num_epochs: 100 # 训练轮数
  start_epoch: 0 # 开始轮数
  end_epoch: 80 # 结束轮数
  learning_rate: 0.0001 # 学习率
  lr_decay: 0.5 # 学习率衰减
  lr_decay_epoch: 10 # 学习率衰减轮数
  lr_decay_start_epoch: 20 # 学习率衰减开始轮数
  lr_decay_patience: 3 # 学习率衰减等待轮数
  lr_decay_min: 0.00001 # 学习率最小值
  lr_decay_state: 0 # 学习率衰减状态
  lr_decay_factor: 0.5 # 学习率衰减因子
  lr_decay_patience: 3 # 学习率衰减等待轮数
  


testing: # 测试
  batch_size: 128 # 批大小
  error_rate_type: cer  # 错误率类型
  decoding_method: ctc_beam_search # 解码方法
  lang_model_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm # 语言模型路径
  alpha: 1.9 # 语言模型权重
  beta: 5.0 # 语言模型权重
  beam_size: 300 # 搜索宽度
  cutoff_prob: 0.99 # 概率截断
  cutoff_top_n: 40 # 概率截断
  num_proc_bsearch: 10 # 搜索进程数


decoding: # 解码
  batch_size: 128
  error_rate_type: cer 
  decoding_method: ctc_beam_search
  lang_model_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm
  alpha: 1.9
  beta: 5.0
  beam_size: 300
  cutoff_prob: 0.99
  cutoff_top_n: 40
  num_proc_bsearch: 10

inference: # 推理
  batch_size: 128
  error_rate_type: cer 
  decoding_method: ctc_beam_search
  lang_model_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm
  alpha: 1.9
  beta: 5.0
  beam_size: 300
  cutoff_prob: 0.99
  cutoff_top_n: 40
  num_proc_bsearch: 10

# Path: data.yaml
